### ISSUE TITLE
Compatibility with Infinispan 6 or 7

### ISSUE THREAD

**Issue by kalkrishnan** [infinispan/infinispan-cachestore-cassandra#2]
Does this work with either? There doesn't seem to be a module for Cassandra in either and the configuration does not load.

**Comment by galderz** [comment]
What are the problems with Infinispan 6/7?

This module's maintenance has been left to the Infinispan community to evolve it as and when needed, hence we don't regularly release it.

**Comment by kalkrishnan** [comment]
Well 6/7 don't seem to come with the module which I found on some forum and not anywhere in there doc. And the module that I found online and tried to include does not work at all. Seems like they have given up and just point to JDBC or a File Store. Disappointing.

**Comment by tristantarrant** [comment]
I contributed the Cassandra cache store a long time ago. When the Infinispan persistence SPI was rewritten in 6.0, many of the cache stores were not updated since there didn't seem to be any interest in them. It would be lovely if you could pick this up and port the code to the new SPI. We will definitely support you and help you as much as we can.

**Comment by kalkrishnan** [comment]
I actually have thought about doing that. What is bothersome is that the Infinispan website mentions all these various cache stores which apparently then don't work with the latest versions available.

**Comment by tristantarrant** [comment]
Thanks to @jmarkos this is now done. Will be released as part of the 8.2 cycle.
